### ISSUE TITLE
Provide shell files

### ISSUE THREAD

**Issue by WouterJ** [WouterJ/fred#1]
* [ ] `bin/fred.php` should be renamed to `bin/fred` and have a sebang
* [ ] `bin/fred.bat` should be created to support windows

**Comment by xabbuh** [comment]
The `fred.bat` file isn't needed anymore for Windows?

**Comment by WouterJ** [comment]
@xabbuh, I've choosen to use Composer as the only installation method of Fred (with 1.0, I'll also provide phar file). Composer already takes care of providing a bat file for windows.

**Comment by xabbuh** [comment]
@WouterJ Thanks for the explanation.
